// Generated by https://quicktype.io

export interface ICommunities {
  id: string;
  name: string;
  description: string;
  color: string;
  createdAt: string;
  users: any[];
  Event: any[];
  membersCount: number;
}
