// Generated by https://quicktype.io

export interface IEventReportResponse {
  event: IEvent;
  consumables: IConsumable[];
  assistanceTickets: IAssistanceTicket[];
  consumablesTickets: IConsumablesTicket[];
}

export interface IAssistanceTicket {
  id: string;
  isActive: boolean;
  wasPresent: boolean;
  scannedAt: null;
  createdAt: string;
  updatedAt: string;
  eventId: string;
  userId: string;
  user: IUser;
}

export interface IUser {
  id: string;
  name: string;
  lastname: string;
  email: string;
  isActive: boolean;
}

export interface IConsumable {
  id: string;
  name: string;
}

export interface IConsumablesTicket {
  id: string;
  isActive: boolean;
  isConsumed: boolean;
  consumedBy: null;
  createdAt: string;
  eventId: string;
  userId: string;
  consumableId: string;
  user: IUser;
  consumable: IConsumable;
}

export interface IEvent {
  id: string;
  title: string;
  description: string;
  dateTime: string;
  score: number;
}
